project_name: aht20

release:
  github:
    owner: ripienaar
    name: aht20
  name_template: "Release {{.Version}}"
  draft: true

changelog:
  skip: true

builds:
  - main: aht20.go
    id: aht20
    binary: aht20
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - name_template: "aht20-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
